# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "94495a2e92cbad69e2e2f6d5c3a5a7aecc5e7057c37cb5111890c2236b84c625"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "660c790b39e22d654c3d086bfdcdc0335ac93ad818df4c36d4c3d2a3e254cdee"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ead28bd51d96ef3159be1f60d5bafae4ac426300442cb117fc5257f2bf94441"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eef6ded31730cdc0ff5d90434be3137b73d19b707824411ed8e0910d4df7643d"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orion"
  desc "The reliability layer of the agentic SDLC — a proof-gated harness from intent to independently proven software"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orion"]
    end
  end

  # No zap stanza required

end
