# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "255222dce0d2e56a146d5afa9c399f62faee3ef10ad1cbd8bb017b5b7411bab6"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abd15ea798fc417bf2a1fcdb3cbacd50819c87d71b2993a9ec79c4c505de17a9"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "425b32c6bbf8a217df4433ed63a6d7a49478a6769dc36666e7b1275cc53ccaea"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "da2a4f40e1bc889d02ca684085f8e0ea0255dc034d1d5b89adf4ece2199e2138"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orion"
  desc "The reliability layer of the agentic SDLC — a proof-gated harness from intent to independently proven software"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orion"]
    end
  end

  # No zap stanza required

end
