# This file was generated by GoReleaser. DO NOT EDIT.
cask "orion" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4734765b1bfe3e5c06725a6fb9830ff49f5ef9ca66dd2558103175c12a32d1ed"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93dc416d7c62be282a2f80a569f57b1f544ea589f1eb3cb37be7b273d955d80b"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "119d78b7fea6830b438a599d987db5f96043bea6b2afaec010a5ce98045e69d2"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e31869fba7175113df3eb64eff1df4b87b7d93edd1f5eeee014f951fb995cbf"
      url "https://github.com/revelara-ai/orion/releases/download/v#{version}/orion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orion"
  desc "The reliability layer of the agentic SDLC — a proof-gated harness from intent to independently proven software"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orion"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/orion"]
    end
  end

  # No zap stanza required

end
