# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvl" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "3c856c021bc2e1d1a2376177368da9da5172e79d1204b0a8f77a1b9184a7dba7"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "528a02265563e53d21edaef499a2b10c931d45a40af8106be6c7280b2dca4737"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c5395e7156823107cb16834e6667eb05f4ac83528d9aaed02ba809492a08280"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3b8463c69efdf87e53bf2341022bb990279719036fffeb954022ed0c4c73c3f"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rvl"
  desc "Revelara CLI — scan your codebase for reliability risks"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvl"]
    end
  end

  # No zap stanza required

end
