# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvl" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "98707d57d18bffc1bc6997caf4b52b24814b7f48961902623e4555fbfd4ccbc1"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c84d53913badfcd00f31d4950bf486f113794b44a92d9307153e804357bcd24d"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c22ce06d6a8c69bbd2e1993b729f5ca8cbe68230b0183e508c6ab9bd355863aa"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "239085d56b85eefc9c486fd47b9760575c2d02cccbc71f61ebc301d33f3a3d29"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rvl"
  desc "Revelara CLI — scan your codebase for reliability risks"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvl"]
    end
  end

  # No zap stanza required

end
