# This file was generated by GoReleaser. DO NOT EDIT.
cask "rvl" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "ee2048f823ae49e86b77b0a79fa9bca573a6c962089c99e74cd0b86b742cca23"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8a68839069873632b3d851bed994ddfae4123b64b95cf74574e69e9ceb3866d"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5acc882a4e8b14bc66423630974ff5a38c709afcd1c4c2db816b717df87201d"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0997026f206c4c721931072efe35ded258d63e7c813685db56ee8053542e0b00"
      url "https://github.com/revelara-ai/rvl-cli/releases/download/v#{version}/rvl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rvl"
  desc "Revelara CLI — scan your codebase for reliability risks"
  homepage "https://revelara.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rvl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvl"]
    end
  end

  # No zap stanza required

end
